/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.prodyna.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the UserData service. Represents a row in the &quot;CUD_UserData&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.prodyna.model.impl.UserDataModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.prodyna.model.impl.UserDataImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserData
 * @see com.prodyna.model.impl.UserDataImpl
 * @see com.prodyna.model.impl.UserDataModelImpl
 * @generated
 */
public interface UserDataModel extends BaseModel<UserData> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user data model instance should use the {@link UserData} interface instead.
	 */

	/**
	 * Returns the primary key of this user data.
	 *
	 * @return the primary key of this user data
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user data.
	 *
	 * @param primaryKey the primary key of this user data
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the user data ID of this user data.
	 *
	 * @return the user data ID of this user data
	 */
	public long getUserDataId();

	/**
	 * Sets the user data ID of this user data.
	 *
	 * @param userDataId the user data ID of this user data
	 */
	public void setUserDataId(long userDataId);

	/**
	 * Returns the company ID of this user data.
	 *
	 * @return the company ID of this user data
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this user data.
	 *
	 * @param companyId the company ID of this user data
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this user data.
	 *
	 * @return the user ID of this user data
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user data.
	 *
	 * @param userId the user ID of this user data
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user data.
	 *
	 * @return the user uuid of this user data
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this user data.
	 *
	 * @param userUuid the user uuid of this user data
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the creation date of this user data.
	 *
	 * @return the creation date of this user data
	 */
	public Date getCreationDate();

	/**
	 * Sets the creation date of this user data.
	 *
	 * @param creationDate the creation date of this user data
	 */
	public void setCreationDate(Date creationDate);

	/**
	 * Returns the modified date of this user data.
	 *
	 * @return the modified date of this user data
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this user data.
	 *
	 * @param modifiedDate the modified date of this user data
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the t_ shirt size of this user data.
	 *
	 * @return the t_ shirt size of this user data
	 */
	@AutoEscape
	public String getT_ShirtSize();

	/**
	 * Sets the t_ shirt size of this user data.
	 *
	 * @param t_ShirtSize the t_ shirt size of this user data
	 */
	public void setT_ShirtSize(String t_ShirtSize);

	/**
	 * Returns the date of birth of this user data.
	 *
	 * @return the date of birth of this user data
	 */
	public Date getDateOfBirth();

	/**
	 * Sets the date of birth of this user data.
	 *
	 * @param dateOfBirth the date of birth of this user data
	 */
	public void setDateOfBirth(Date dateOfBirth);

	/**
	 * Returns the glasses of this user data.
	 *
	 * @return the glasses of this user data
	 */
	public boolean getGlasses();

	/**
	 * Returns <code>true</code> if this user data is glasses.
	 *
	 * @return <code>true</code> if this user data is glasses; <code>false</code> otherwise
	 */
	public boolean isGlasses();

	/**
	 * Sets whether this user data is glasses.
	 *
	 * @param glasses the glasses of this user data
	 */
	public void setGlasses(boolean glasses);

	/**
	 * Returns the coffees per day of this user data.
	 *
	 * @return the coffees per day of this user data
	 */
	public int getCoffeesPerDay();

	/**
	 * Sets the coffees per day of this user data.
	 *
	 * @param coffeesPerDay the coffees per day of this user data
	 */
	public void setCoffeesPerDay(int coffeesPerDay);

	/**
	 * Returns the height cm of this user data.
	 *
	 * @return the height cm of this user data
	 */
	public int getHeightCm();

	/**
	 * Sets the height cm of this user data.
	 *
	 * @param heightCm the height cm of this user data
	 */
	public void setHeightCm(int heightCm);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.prodyna.model.UserData userData);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.prodyna.model.UserData> toCacheModel();

	@Override
	public com.prodyna.model.UserData toEscapedModel();

	@Override
	public com.prodyna.model.UserData toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}